on:
  schedule:
    - '0 0 * * *'
  workflow_dispatch: {}

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - run: npx capture-website-cli https://careers.zerodha.com --full-page --output=current.png

      - name: match
        run: npx pixelmatch screenshots/original.png current.png
        continue-on-error: true

      - if: failure() && steps.match.outcome == 'failure'
        run: echo "match failed, webpage may have changed"
