name: match

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - run: |
          npx capture-website-cli https://careers.zerodha.com --full-page --output=current/zerodha-careers.png
          npx capture-website-cli https://www.greensoul.online/products/renewed-vision-gaming-chair?variant=44058865205565 --full-page --output=current/greensoul-vision-chair.png

      - name: match
        run: |
          npx pixelmatch originals/zerodha-careers.png current/zerodha-careers.png
          npx pixelmatch originals/greensoul-vision-chair.png current/greensoul-vision-chair.png
